package lee.code.pets.utils;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.bukkit.entity.EntityType;
import org.bukkit.potion.PotionEffect;
import org.bukkit.potion.PotionEffectType;

@AllArgsConstructor
public enum PetEffects {
  COW(EntityType.COW, new PotionEffect(PotionEffectType.LUCK, 20 * 10, 0)),
  SHEEP(EntityType.SHEEP, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  ALLAY(EntityType.ALLAY, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 1)),
  AXOLOTL(EntityType.AXOLOTL, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 0)),
  BAT(EntityType.BAT, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  CAT(EntityType.CAT, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 0)),
  CAMEL(EntityType.CAMEL, new PotionEffect(PotionEffectType.DAMAGE_RESISTANCE, 20 * 10, 0)),
  CHICKEN(EntityType.CHICKEN, new PotionEffect(PotionEffectType.SLOW_FALLING, 20 * 10, 0)),
  COD(EntityType.COD, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  DONKEY(EntityType.DONKEY, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  FOX(EntityType.FOX, new PotionEffect(PotionEffectType.JUMP, 20 * 10, 0)),
  FROG(EntityType.FROG, new PotionEffect(PotionEffectType.JUMP, 20 * 10, 0)),
  GLOW_SQUID(EntityType.GLOW_SQUID, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  HORSE(EntityType.HORSE, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 1)),
  MUSHROOM_COW(EntityType.MUSHROOM_COW, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 1)),
  MULE(EntityType.MULE, new PotionEffect(PotionEffectType.JUMP, 20 * 10, 0)),
  OCELOT(EntityType.OCELOT, new PotionEffect(PotionEffectType.SLOW_FALLING, 20 * 10, 0)),
  PARROT(EntityType.PARROT, new PotionEffect(PotionEffectType.HEALTH_BOOST, 20 * 10, 1)),
  PIG(EntityType.PIG, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 0)),
  PUFFERFISH(EntityType.PUFFERFISH, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  RABBIT(EntityType.RABBIT, new PotionEffect(PotionEffectType.JUMP, 20 * 10, 1)),
  SALMON(EntityType.SALMON, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 1)),
  SNIFFER(EntityType.SNIFFER, new PotionEffect(PotionEffectType.FAST_DIGGING, 20 * 10, 1)),
  SNOWMAN(EntityType.SNOWMAN, new PotionEffect(PotionEffectType.SLOW_FALLING, 20 * 10, 0)),
  SQUID(EntityType.SQUID, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  STRIDER(EntityType.STRIDER, new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 20 * 10, 0)),
  TADPOLE(EntityType.TADPOLE, new PotionEffect(PotionEffectType.LUCK, 20 * 10, 0)),
  TROPICAL_FISH(EntityType.TROPICAL_FISH, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  TURTLE(EntityType.TURTLE, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  VILLAGER(EntityType.VILLAGER, new PotionEffect(PotionEffectType.HEAL, 20 * 10, 1)),
  WANDERING_TRADER(EntityType.WANDERING_TRADER, new PotionEffect(PotionEffectType.INVISIBILITY, 20 * 10, 0)),
  CAVE_SPIDER(EntityType.CAVE_SPIDER, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  DOLPHIN(EntityType.DOLPHIN, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  ENDERMAN(EntityType.ENDERMAN, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  GOAT(EntityType.GOAT, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  IRON_GOLEM(EntityType.IRON_GOLEM, new PotionEffect(PotionEffectType.HEALTH_BOOST, 20 * 10, 1)),
  LLAMA(EntityType.LLAMA, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 0)),
  PANDA(EntityType.PANDA, new PotionEffect(PotionEffectType.HEAL, 20 * 10, 0)),
  PIGLIN(EntityType.PIGLIN, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  PIGLIN_BRUTE(EntityType.PIGLIN_BRUTE, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  ZOMBIFIED_PIGLIN(EntityType.ZOMBIFIED_PIGLIN, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  POLAR_BEAR(EntityType.POLAR_BEAR, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 0)),
  SKELETON_HORSE(EntityType.SKELETON_HORSE, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 0)),
  SPIDER(EntityType.SPIDER, new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 20 * 10, 1)),
  TRADER_LLAMA(EntityType.TRADER_LLAMA, new PotionEffect(PotionEffectType.LUCK, 20 * 10, 0)),
  WOLF(EntityType.WOLF, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  CREEPER(EntityType.CREEPER, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 1)),
  DROWNED(EntityType.DROWNED, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  ELDER_GUARDIAN(EntityType.ELDER_GUARDIAN, new PotionEffect(PotionEffectType.CONDUIT_POWER, 20 * 10, 1)),
  ENDERMITE(EntityType.ENDERMITE, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 0)),
  ILLUSIONER(EntityType.ILLUSIONER, new PotionEffect(PotionEffectType.INVISIBILITY, 20 * 10, 0)),
  WITHER(EntityType.WITHER, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 1)),
  BLAZE(EntityType.BLAZE, new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 20 * 10, 1)),
  EVOKER(EntityType.EVOKER, new PotionEffect(PotionEffectType.HEAL, 20 * 10, 1)),
  GHAST(EntityType.GHAST, new PotionEffect(PotionEffectType.SLOW_FALLING, 20 * 10, 0)),
  GUARDIAN(EntityType.GUARDIAN, new PotionEffect(PotionEffectType.WATER_BREATHING, 20 * 10, 0)),
  HOGLIN(EntityType.HOGLIN, new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 20 * 10, 1)),
  ZOGLIN(EntityType.ZOGLIN, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 1)),
  HUSK(EntityType.HUSK, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 1)),
  MAGMA_CUBE(EntityType.MAGMA_CUBE, new PotionEffect(PotionEffectType.FIRE_RESISTANCE, 20 * 10, 1)),
  PHANTOM(EntityType.PHANTOM, new PotionEffect(PotionEffectType.SLOW_FALLING, 20 * 10, 0)),
  PILLAGER(EntityType.PILLAGER, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 1)),
  RAVAGER(EntityType.RAVAGER, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 2)),
  SHULKER(EntityType.SHULKER, new PotionEffect(PotionEffectType.LEVITATION, 20 * 10, 1)),
  SILVERFISH(EntityType.SILVERFISH, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 0)),
  SKELETON(EntityType.SKELETON, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 0)),
  SLIME(EntityType.SLIME, new PotionEffect(PotionEffectType.JUMP, 20 * 10, 1)),
  STRAY(EntityType.STRAY, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 1)),
  VEX(EntityType.VEX, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 1)),
  VINDICATOR(EntityType.VINDICATOR, new PotionEffect(PotionEffectType.NIGHT_VISION, 20 * 10, 0)),
  WARDEN(EntityType.WARDEN, new PotionEffect(PotionEffectType.HEALTH_BOOST, 20 * 10, 2)),
  WITCH(EntityType.WITCH, new PotionEffect(PotionEffectType.LUCK, 20 * 10, 1)),
  WITHER_SKELETON(EntityType.WITHER_SKELETON, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 1)),
  ZOMBIE(EntityType.ZOMBIE, new PotionEffect(PotionEffectType.INCREASE_DAMAGE, 20 * 10, 0)),
  ZOMBIE_VILLAGER(EntityType.ZOMBIE_VILLAGER, new PotionEffect(PotionEffectType.REGENERATION, 20 * 10, 0)),
  ENDER_DRAGON(EntityType.ENDER_DRAGON, new PotionEffect(PotionEffectType.HEALTH_BOOST, 20 * 10, 5)),
  ZOMBIE_HORSE(EntityType.ZOMBIE_HORSE, new PotionEffect(PotionEffectType.HEALTH_BOOST, 20 * 10, 1)),
  BEE(EntityType.BEE, new PotionEffect(PotionEffectType.SPEED, 20 * 10, 1)),

  ;

  @Getter private final EntityType entityType;
  @Getter private final PotionEffect potionEffect;
}

