name: $name
version: $version
main: lee.code.pets.Pets
description: $description
author: Lee
api-version: "$apiVersion"
depend: [ProtocolLib, GoldmanPlayerData]
commands:
  pets:
    description: Main pets command.
    permission: pets.command.pets
    aliases: [pet]
